// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkipitChat.Data;

namespace SkipitChat.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201022135655_SeedMore")]
    partial class SeedMore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasColumnType("varchar(256)")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex");

                    b.ToTable("AspNetUsers");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Name")
                        .HasColumnType("varchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("SkipitChat.Domain.Accessibility", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("BikeParking")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<bool>("DisabledService")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Elevator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Escalator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Stairs")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("StationName")
                        .HasColumnType("longtext");

                    b.Property<bool>("TicketMachine")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("Toilet")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("WaitingRoom")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Accessiblities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bb38fc53-bf4d-4d07-9d9d-882e5b84fa67"),
                            BikeParking = true,
                            Comment = "",
                            DisabledService = true,
                            Elevator = true,
                            Escalator = true,
                            Stairs = true,
                            StationName = "Station 1",
                            TicketMachine = true,
                            Toilet = true,
                            WaitingRoom = true
                        },
                        new
                        {
                            Id = new Guid("3aa9b509-fed5-43c5-8f2c-f46440e26804"),
                            BikeParking = false,
                            Comment = "",
                            DisabledService = false,
                            Elevator = false,
                            Escalator = false,
                            Stairs = false,
                            StationName = "Station 2",
                            TicketMachine = false,
                            Toilet = false,
                            WaitingRoom = false
                        },
                        new
                        {
                            Id = new Guid("2fb35348-618c-4bd8-ba16-e342c7041a75"),
                            BikeParking = false,
                            Comment = "",
                            DisabledService = false,
                            Elevator = true,
                            Escalator = false,
                            Stairs = false,
                            StationName = "Station 3",
                            TicketMachine = true,
                            Toilet = true,
                            WaitingRoom = false
                        });
                });

            modelBuilder.Entity("SkipitChat.Domain.CityPass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<float>("CityPass4Price")
                        .HasColumnType("float");

                    b.Property<float>("CityPass99Price")
                        .HasColumnType("float");

                    b.Property<int>("DurationInHour")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CityPasses");

                    b.HasData(
                        new
                        {
                            Id = new Guid("363aef28-0261-469b-a428-488979bee6fa"),
                            CityPass4Price = 2345f,
                            CityPass99Price = 3000f,
                            DurationInHour = 244
                        },
                        new
                        {
                            Id = new Guid("5e00fc58-3bb1-4aec-ba1c-c372abe71a00"),
                            CityPass4Price = 55f,
                            CityPass99Price = 90f,
                            DurationInHour = 4
                        },
                        new
                        {
                            Id = new Guid("7dbf1d64-f612-4812-be57-5d834e172190"),
                            CityPass4Price = 599f,
                            CityPass99Price = 700f,
                            DurationInHour = 24
                        });
                });

            modelBuilder.Entity("SkipitChat.Domain.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("SkipitChat.Domain.Zone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<float>("Animal")
                        .HasColumnType("float");

                    b.Property<float>("Bycicle")
                        .HasColumnType("float");

                    b.Property<int>("DurationInMinute")
                        .HasColumnType("int");

                    b.Property<float>("PriceAdult")
                        .HasColumnType("float");

                    b.Property<float>("PriceChildren")
                        .HasColumnType("float");

                    b.Property<float>("PriceDisabled")
                        .HasColumnType("float");

                    b.Property<float>("PriceElderly")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Zones");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Animal = 20f,
                            Bycicle = 20f,
                            DurationInMinute = 120,
                            PriceAdult = 10f,
                            PriceChildren = 5f,
                            PriceDisabled = 5f,
                            PriceElderly = 5f
                        },
                        new
                        {
                            Id = 3,
                            Animal = 20f,
                            Bycicle = 9f,
                            DurationInMinute = 170,
                            PriceAdult = 6f,
                            PriceChildren = 4f,
                            PriceDisabled = 5f,
                            PriceElderly = 7f
                        },
                        new
                        {
                            Id = 4,
                            Animal = 20f,
                            Bycicle = 20f,
                            DurationInMinute = 120,
                            PriceAdult = 17f,
                            PriceChildren = 7f,
                            PriceDisabled = 5f,
                            PriceElderly = 7f
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
